from gym_sail_race.envs.motorboat_env import MotorboatEnv
from gym_sail_race.envs.sailboat_env import SailboatRaceEnv
from gym_sail_race.envs.sailboat_env import SailboatDiscreteEnv
from gym_sail_race.envs.boat_env import BoatEnv
from gym_sail_race.envs.boat_env import BoatDiscreteEnv
from gym_sail_race.envs.sailboat_env import SailboatRaceEnv2Mark
from gym_sail_race.envs.sailboat_env import SailboatRaceEnvJibePractice